apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: common
  labels:
    k8s-app: elasticsearch
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "Elasticsearch"
spec:
  ports:
  - port: 9200
    protocol: TCP
    targetPort: 9200
  selector:
    k8s-app: elasticsearch
---
# RBAC authn and authz
apiVersion: v1
kind: ServiceAccount
metadata:
  name: elasticsearch
  namespace: common
  labels:
    k8s-app: elasticsearch
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: elasticsearch
  labels:
    k8s-app: elasticsearch
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
rules:
- apiGroups:
  - ""
  resources:
  - "services"
  - "namespaces"
  - "endpoints"
  verbs:
  - "get"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: common
  name: elasticsearch
  labels:
    k8s-app: elasticsearch
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
subjects:
- kind: ServiceAccount
  name: elasticsearch
  namespace: common
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: elasticsearch
  apiGroup: ""
---
# Elasticsearch deployment itself
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: common
  labels:
    k8s-app: elasticsearch
    version: v7.8.1
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  serviceName: elasticsearch
  replicas: 1
  selector:
    matchLabels:
      k8s-app: elasticsearch
      version: v7.8.1
  template:
    metadata:
      labels:
        k8s-app: elasticsearch
        version: v7.8.1
        kubernetes.io/cluster-service: "true"
    spec:
      serviceAccountName: elasticsearch
      containers:
      - image: docker.io/elasticsearch:7.8.1
        name: elasticsearch
        #resources:
          # need more cpu upon initialization, therefore burstable class
          #limits:
          #  cpu: 1000m
          #requests:
          #  cpu: 100m
        ports:
        - containerPort: 9200  #容器端口
          name: db
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
#        volumeMounts:
#          - name: nfs
#            mountPath: /usr/share/elasticsearch/data #elasticsearch存储数据路径
        env:
        - name: "NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: discovery.type   # 跳过集群检测
          value: single-node
#      volumes:
#      - name: nfs #挂载pvc作为es存储，重启pod后数据保留。
#        persistentVolumeClaim:
#          claimName: k8s-elk-pvc
#      volumes:
#        - name: nfs
#          nfs:
#            server: nfs.com   #自行更改nfs 服务器
#            path: "/elasticsearch/data"
      # Elasticsearch requires vm.max_map_count to be at least 262144.
      # If your OS already sets up this number to a higher value, feel free
      # to remove this init container.
      initContainers:
      - image: alpine:3.12
        command: ["/sbin/sysctl", "-w", "vm.max_map_count=262144"]
        name: elasticsearch-init
        securityContext:
          privileged: true