apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: common
  labels:
    k8s-app: kibana
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: kibana
  template:
    metadata:
      labels:
        k8s-app: kibana
      #annotations:
      #  seccomp.security.alpha.kubernetes.io/pod: 'docker/default'
    spec:
      containers:
      - name: kibana
        image: kibana:7.8.1
        resources:
          # need more cpu upon initialization, therefore burstable class
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        env:
          - name: ELASTICSEARCH_URL
            value: http://elasticsearch:9200
          #- name: SERVER_BASEPATH
          #  value: / #/api/v1/namespaces/kube-system/services/kibana/proxy
        ports:
        - containerPort: 5601  #容器端口
          name: kibana
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: common
  labels:
    k8s-app: kibana
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "Kibana"
spec:
  #type: NodePort  #暴露访问端口
  ports:
  - port: 5601
    protocol: TCP
    targetPort: kibana
    #nodePort: 30003 
  selector:
    k8s-app: kibana
---
#apiVersion: extensions/v1beta1
#kind: Ingress
#metadata:
#  name: traefik-kibana
#  namespace: common
#spec:
#  rules:
#  - host: local.kibana.com  #自定义域名访问
#    http:
#      paths:
#      - path: /
#        backend:
#          serviceName: kibana
#          servicePort: 5601